use std::fs;
use std::path::Path;

///  `CoreGenerator`: The static HTTP router and framework entry point generator.
///
/// This build-time struct introspects the file system to implement an ultra-fast `O(1)` routing
/// mechanism with zero memory allocation. It also handles convention-over-configuration routing,
/// such as automatically resolving `PascalCase` file names to `kebab-case` URI endpoints.
///
/// # Architecture
/// Instead of relying on runtime routing trees (like `axum` or `actix`), `CoreGenerator` generates
/// a static `match` statement at compile-time for the Hyper HTTP server, ensuring absolute maximum
/// performance and guaranteeing that 404s can be statically identified.
///
/// # Examples
///
/// ```no_run
/// use lightx::core_generator::CoreGenerator;
///
/// let generator = CoreGenerator::new("./handlers", "./i18n", &std::env::var("OUT_DIR").unwrap());
/// generator.generate_core().expect("Failed to generate the Core Router");
/// ```
pub struct CoreGenerator {
    handlers_dir: String,
    i18n_dir: String,
    out_dir: String,
}

impl CoreGenerator {
    /// Creates a new `CoreGenerator` instance.
    ///
    /// # Arguments
    ///
    /// * `handlers_dir` - The root directory containing the TOML handler specifications.
    /// * `out_dir` - The `OUT_DIR` provided by Cargo during the build phase.
    pub fn new(handlers_dir: &str, i18n_dir: &str, out_dir: &str) -> Self {
        Self {
            handlers_dir: handlers_dir.to_string(),
            i18n_dir: i18n_dir.to_string(),
            out_dir: out_dir.to_string(),
        }
    }

    fn visit_dirs(dir: &Path, cb: &mut dyn FnMut(&fs::DirEntry)) -> std::io::Result<()> {
        if dir.is_dir() {
            for entry in fs::read_dir(dir)? {
                let entry = entry?;
                let path = entry.path();
                if path.is_dir() {
                    Self::visit_dirs(&path, cb)?;
                } else {
                    cb(&entry);
                }
            }
        }
        Ok(())
    }

    /// Helper to convert a file system path into a valid Rust `PascalCase` struct identifier.
    /// (e.g., "api/AdminCreation" -> "ApiAdminCreation")
    fn to_pascal_name(rel_path: &Path) -> String {
        let mut name = String::new();
        for component in rel_path.components() {
            if let std::path::Component::Normal(os_str) = component {
                let mut s = os_str.to_string_lossy().into_owned();
                if s.ends_with(".toml") {
                    s.truncate(s.len() - 5);
                }
                let mut capitalize_next = true;
                for c in s.chars() {
                    if c == '-' || c == '_' || c == '{' || c == '}' || c == '.' {
                        capitalize_next = true;
                    } else if capitalize_next {
                        name.push_str(&c.to_uppercase().to_string());
                        capitalize_next = false;
                    } else {
                        name.push(c);
                    }
                }
            }
        }
        name
    }

    /// Helper to convert a relative file path into a `kebab-case` URI route pattern.
    /// (e.g., "api/AdminCreation.toml" -> "/api/admin-creation")
    fn to_match_pattern(rel_path: &Path) -> String {
        let mut segments = Vec::new();
        for component in rel_path.components() {
            if let std::path::Component::Normal(os_str) = component {
                let mut s = os_str.to_string_lossy().into_owned();
                if s.ends_with(".toml") {
                    s.truncate(s.len() - 5);
                }
                segments.push(Self::to_kebab_case(&s));
            }
        }

        let mut pattern = String::new();
        for seg in segments {
            pattern.push('/');
            pattern.push_str(&seg);
        }
        // Always prefixed by `/`
        pattern
    }

    /// Helper to convert PascalCase to kebab-case (e.g., 'AdminCreation' -> 'admin-creation')
    fn to_kebab_case(s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() {
                if i > 0 {
                    result.push('-');
                }
                result.push(c.to_ascii_lowercase());
            } else {
                result.push(c);
            }
        }
        result
    }

    ///  Parses handlers and generates the global `route_request` function
    pub fn generate_core(&self) -> Result<(), Box<dyn std::error::Error>> {
        let dest_path = Path::new(&self.out_dir).join("lightx_core_generated.rs");
        let handlers_path = Path::new(&self.handlers_dir);

        let mut code = String::from(
            "// =====================================================================\n// THIS FILE IS AUTO-GENERATED BY LIGHTX. DO NOT EDIT.\n// =====================================================================\n\n",
        );
        code.push_str(
            "// Single Source of Truth: Convention over Configuration (Handlers directory)\n\n",
        );

        let mut dbs: Vec<(String, String, String)> = Vec::new();
        for (key, val) in std::env::vars() {
            if !key.ends_with("URL") {
                continue;
            }
            let dialect = if val.starts_with("sqlite") {
                "sqlite"
            } else if val.starts_with("mysql") || val.starts_with("mariadb") {
                "mysql"
            } else if val.starts_with("postgres") {
                "postgres"
            } else {
                continue;
            };

            let lower = key.to_lowercase();
            let prefix = lower.replace("_database_url", "").replace("_url", "");
            let pool_name = if prefix.is_empty() || prefix == "database" || prefix == dialect {
                format!("{}_pool", dialect)
            } else {
                format!("{}_pool", prefix)
            };
            dbs.push((key, pool_name, dialect.to_string()));
        }
        dbs.sort_by(|a, b| a.1.cmp(&b.1));

        let mut req_ctx_fields = String::new();
        let mut factory_fields = String::new();
        let mut factory_new_impl = String::new();
        let mut factory_init = String::new();
        let mut create_ctx_fields = String::new();
        let mut commit_ctx_impl = String::new();

        for (env_var, pool_name, dialect) in &dbs {
            let tx_name = pool_name.replace("_pool", "_tx");
            let (pool_type, tx_type, opt_type) = match dialect.as_str() {
                "sqlite" => (
                    "sqlx::SqlitePool",
                    "sqlx::Sqlite",
                    "sqlx::sqlite::SqlitePoolOptions",
                ),
                "mysql" => (
                    "sqlx::MySqlPool",
                    "sqlx::MySql",
                    "sqlx::mysql::MySqlPoolOptions",
                ),
                "postgres" => (
                    "sqlx::PgPool",
                    "sqlx::Postgres",
                    "sqlx::postgres::PgPoolOptions",
                ),
                _ => unreachable!(),
            };

            req_ctx_fields.push_str(&format!("    pub {}: {},\n", pool_name, pool_type));
            req_ctx_fields.push_str(&format!(
                "    pub {}: Option<sqlx::Transaction<'static, {}>>,\n",
                tx_name, tx_type
            ));
            factory_fields.push_str(&format!("    pub {}: {},\n", pool_name, pool_type));
            factory_new_impl.push_str(&format!("        let url_{} = std::env::var(\"{}\").map_err(|_| lightx::core::AppError::SystemError {{ msg: \"Missing config {}\".to_string(), file: file!(), line: line!() }})?;\n", pool_name, env_var, env_var));
            factory_new_impl.push_str(&format!("        let {} = {}::new().connect_lazy(&url_{}).map_err(|e| lightx::core::AppError::SystemError {{ msg: e.to_string(), file: file!(), line: line!() }})?;\n", pool_name, opt_type, pool_name));
            factory_init.push_str(&format!("            {},\n", pool_name));
            create_ctx_fields.push_str(&format!(
                "            {}: self.{}.clone(),\n",
                pool_name, pool_name
            ));
            create_ctx_fields.push_str(&format!("            {}: None,\n", tx_name));
            commit_ctx_impl.push_str(&format!("            if let Some(tx) = ctx.{}.take() {{ tx.commit().await.map_err(|e| e.to_string())?; }}\n", tx_name));
        }

        code.push_str(&format!(r#"
pub struct RequestContext {{
    pub raw_body: lightx::ext::bytes::Bytes,
    pub global_state: std::sync::Arc<lightx::ext::tokio::sync::broadcast::Sender<lightx::ext::bytes::Bytes>>,
    pub rate_limiter: std::sync::Arc<lightx::ext::moka::sync::Cache<(std::net::IpAddr, &'static str), std::sync::Arc<std::sync::atomic::AtomicU32>>>,
    pub response_cache: std::sync::Arc<lightx::ext::moka::sync::Cache<String, (lightx::ext::hyper::StatusCode, lightx::ext::hyper::HeaderMap, lightx::ext::bytes::Bytes, std::time::Instant)>>,
    pub client_ip: std::net::IpAddr,
    pub user_id: std::option::Option<String>,
    pub headers: lightx::ext::hyper::HeaderMap,
    pub raw_req: Option<lightx::ext::hyper::Request<lightx::ext::hyper::body::Incoming>>,
{}
}}

pub struct AppContextFactory {{
    pub global_state: std::sync::Arc<lightx::ext::tokio::sync::broadcast::Sender<lightx::ext::bytes::Bytes>>,
    pub rate_limiter: std::sync::Arc<lightx::ext::moka::sync::Cache<(std::net::IpAddr, &'static str), std::sync::Arc<std::sync::atomic::AtomicU32>>>,
    pub response_cache: std::sync::Arc<lightx::ext::moka::sync::Cache<String, (lightx::ext::hyper::StatusCode, lightx::ext::hyper::HeaderMap, lightx::ext::bytes::Bytes, std::time::Instant)>>,
{}
}}

impl AppContextFactory {{
    pub async fn new() -> Result<Self, lightx::core::AppError> {{
{}
        Ok(Self {{
            global_state: std::sync::Arc::new(lightx::ext::tokio::sync::broadcast::channel(1024).0),
            rate_limiter: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().build()),
            response_cache: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().max_capacity(10_000).build()),
{}
        }})
    }}
}}

impl lightx::server::ContextFactory for AppContextFactory {{
    type Context = RequestContext;
    fn create_context(&self, peer_addr: std::net::IpAddr, headers: lightx::ext::hyper::HeaderMap, raw_body: lightx::ext::bytes::Bytes, raw_req: Option<lightx::ext::hyper::Request<lightx::ext::hyper::body::Incoming>>) -> Self::Context {{
        RequestContext {{
            raw_body,
            global_state: self.global_state.clone(),
            rate_limiter: self.rate_limiter.clone(),
            response_cache: self.response_cache.clone(),
            client_ip: peer_addr,
            user_id: None,
            headers,
            raw_req,
{}
        }}
    }}

    fn commit_context<'a>(&'a self, ctx: &'a mut Self::Context) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), String>> + Send + 'a>> {{
        Box::pin(async move {{
{}
            Ok(())
        }})
    }}
}}
"#, req_ctx_fields, factory_fields, factory_new_impl, factory_init, create_ctx_fields, commit_ctx_impl));

        code.push_str("/// Retrieves system log translations with zero overhead.\n");
        code.push_str("pub fn get_system_log(key: &str, lang: &str) -> &'static str {\n");
        code.push_str("    match (key, lang) {\n");
        if let Ok(entries) = fs::read_dir(Path::new(&self.i18n_dir)) {
            for entry in entries.filter_map(|e| e.ok()) {
                if entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false) {
                    let lang = entry.file_name().to_string_lossy().to_string();
                    let sys_toml = entry.path().join("system.toml");
                    if let Ok(content) = fs::read_to_string(&sys_toml)
                        && let Ok(value) = content.parse::<toml::Value>()
                        && let Some(server) = value.get("server")
                    {
                        if let Some(start) = server.get("start").and_then(|v| v.as_str()) {
                            code.push_str(&format!(
                                "        (\"server.start\", \"{}\") => \"{}\",\n",
                                lang, start
                            ));
                        }
                        if let Some(stop) = server.get("stop").and_then(|v| v.as_str()) {
                            code.push_str(&format!(
                                "        (\"server.stop\", \"{}\") => \"{}\",\n",
                                lang, stop
                            ));
                        }
                    }
                }
            }
        }
        code.push_str("        (\"server.start\", _) => \"Starting the server...\",\n");
        code.push_str("        (\"server.stop\", _) => \"Server stopped.\",\n");
        code.push_str("        _ => \"System trace\",\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");

        code.push_str(
            "///  The global entry point that routes HTTP requests to the correct AOP Pipeline.\n",
        );
        code.push_str("/// Runs in O(1) time complexity with zero allocation.\n");
        code.push_str("pub async fn route_request(method: &str, uri: &str, ctx: &mut crate::RequestContext) -> Result<lightx::ext::hyper::Response<lightx::ext::http_body_util::combinators::BoxBody<lightx::ext::bytes::Bytes, Box<dyn std::error::Error + Send + Sync + 'static>>>, lightx::core::AppError> {\n");
        code.push_str("    use lightx::ext::tracing::Instrument;\n");
        code.push_str("    use lightx::ext::tracing_opentelemetry::OpenTelemetrySpanExt;\n");
        code.push_str("    let span = lightx::ext::tracing::info_span!(\"http_request\", http.method = %method, http.uri = %uri, client.ip = %ctx.client_ip, user.id = lightx::ext::tracing::field::Empty);\n");
        code.push_str("    let parent_context = lightx::ext::opentelemetry::global::get_text_map_propagator(|propagator| {\n");
        code.push_str("        propagator.extract(&lightx::ext::opentelemetry_http::HeaderExtractor(&ctx.headers))\n");
        code.push_str("    });\n");
        code.push_str("    let _ = span.set_parent(parent_context);\n");
        code.push_str("    static ROUTER: std::sync::OnceLock<lightx::ext::matchit::Router<u16>> = std::sync::OnceLock::new();\n");
        code.push_str("    async {\n");
        code.push_str("    let router = ROUTER.get_or_init(|| {\n");
        code.push_str("        let mut r = lightx::ext::matchit::Router::new();\n");

        let mut next_id = 0u16;

        if handlers_path.exists() {
            let mut toml_files = Vec::new();
            Self::visit_dirs(handlers_path, &mut |entry| {
                if entry.path().extension().unwrap_or_default() == "toml" {
                    toml_files.push(entry.path());
                }
            })?;

            for (i, path) in toml_files.iter().enumerate() {
                let current_id = i as u16;
                let rel_path = path.strip_prefix(handlers_path).unwrap();
                let pattern = Self::to_match_pattern(rel_path);
                // Inserting with trailing catch-all to mimic original `_params @ ..` capability
                code.push_str(&format!(
                    "        r.insert(\"{}/*rest\", {}).unwrap();\n",
                    pattern, current_id
                ));
                code.push_str(&format!(
                    "        r.insert(\"{}\", {}).unwrap();\n",
                    pattern, current_id
                ));
                next_id = current_id + 1;
            }
        }

        let swagger_id = next_id;
        code.push_str(&format!(
            "        r.insert(\"/swagger\", {}).unwrap();\n",
            swagger_id
        ));
        code.push_str("        r\n");
        code.push_str("    });\n\n");

        code.push_str("    let uri_clean = uri.split('?').next().unwrap_or(uri);\n");
        code.push_str("    if let Ok(matched) = router.at(uri_clean) {\n");
        code.push_str("        match matched.value {\n");

        if handlers_path.exists() {
            let mut toml_files = Vec::new();
            Self::visit_dirs(handlers_path, &mut |entry| {
                if entry.path().extension().unwrap_or_default() == "toml" {
                    toml_files.push(entry.path());
                }
            })?;

            for (i, path) in toml_files.iter().enumerate() {
                let current_node = i as u16;
                let rel_path = path.strip_prefix(handlers_path).unwrap();
                let handler_name = format!("{}Handler", Self::to_pascal_name(rel_path));

                let content = fs::read_to_string(path).unwrap_or_default();
                let is_static = if let Ok(toml_val) = content.parse::<toml::Value>() {
                    toml_val.get("type").and_then(|t| t.as_str()) == Some("static")
                } else {
                    false
                };

                if is_static {
                    let toml_val: toml::Value = content.parse().unwrap();
                    let dir = toml_val
                        .get("dir")
                        .and_then(|v| v.as_str())
                        .unwrap_or("./static");
                    let absolute_dir =
                        std::fs::canonicalize(dir).unwrap_or_else(|_| Path::new(dir).to_path_buf());

                    code.push_str(&format!("            {} => {{\n", current_node));
                    code.push_str("                let file_path = matched.params.get(\"rest\").unwrap_or(\"\");\n");
                    code.push_str("                match file_path {\n");

                    // Walk directory and pre-compute ETags using SHA256 at Build Time
                    if absolute_dir.exists() {
                        let mut stack = vec![absolute_dir.clone()];
                        while let Some(current_path) = stack.pop() {
                            if current_path.is_dir() {
                                if let Ok(entries) = fs::read_dir(&current_path) {
                                    for entry in entries.filter_map(Result::ok) {
                                        stack.push(entry.path());
                                    }
                                }
                            } else if current_path.is_file() {
                                let file_rel_path = current_path
                                    .strip_prefix(&absolute_dir)
                                    .unwrap()
                                    .to_string_lossy()
                                    .replace("\\", "/");

                                use sha2::Digest;
                                let mut hasher = sha2::Sha256::new();
                                hasher.update(fs::read(&current_path).unwrap());
                                let mut hex_hash = String::new();
                                for b in hasher.finalize() {
                                    hex_hash.push_str(&format!("{:02x}", b));
                                }
                                let etag = format!("\\\"{}\\\"", hex_hash);
                                let abs_str = current_path.to_string_lossy().replace("\\", "/");

                                code.push_str(&format!(
                                    "                    \"/{}\" => {{\n",
                                    file_rel_path
                                ));
                                code.push_str(&format!(
                                    "                        let etag = \"{}\";\n",
                                    etag
                                ));
                                code.push_str("                        if let Some(client_etag) = ctx.headers.get(lightx::ext::hyper::header::IF_NONE_MATCH) {\n");
                                code.push_str("                            if let Ok(client_etag_str) = client_etag.to_str() {\n");
                                code.push_str("                                if client_etag_str == etag {\n");
                                code.push_str("                                    return Ok(lightx::ext::hyper::Response::builder().status(304).body(lightx::ext::http_body_util::BodyExt::boxed(lightx::ext::http_body_util::BodyExt::map_err(lightx::ext::http_body_util::Empty::new(), |e| Box::new(e) as Box<dyn std::error::Error + Send + Sync + 'static>))).unwrap());\n");
                                code.push_str("                                }\n");
                                code.push_str("                            }\n");
                                code.push_str("                        }\n");

                                code.push_str(&format!("                        let file = lightx::ext::tokio::fs::File::open(\"{}\").await.map_err(|_| lightx::core::AppError::RouteNotFound)?;\n", abs_str));
                                code.push_str("                        let stream = lightx::ext::tokio_util::io::ReaderStream::new(file);\n");
                                code.push_str("                        use lightx::ext::futures_util::StreamExt;\n");
                                code.push_str("                        let mapped_stream = stream.map(|res| res.map(lightx::ext::hyper::body::Frame::data));\n");
                                code.push_str("                        let body = lightx::ext::http_body_util::StreamBody::new(mapped_stream);\n");
                                code.push_str("                        let boxed_body = lightx::ext::http_body_util::BodyExt::boxed(lightx::ext::http_body_util::BodyExt::map_err(body, |e| Box::new(e) as Box<dyn std::error::Error + Send + Sync + 'static>));\n");

                                // Determine mime type roughly for pedagogical success
                                let mime = if file_rel_path.ends_with(".html") {
                                    "text/html"
                                } else if file_rel_path.ends_with(".css") {
                                    "text/css"
                                } else if file_rel_path.ends_with(".js") {
                                    "application/javascript"
                                } else if file_rel_path.ends_with(".svg") {
                                    "image/svg+xml"
                                } else {
                                    "application/octet-stream"
                                };

                                code.push_str(&format!("                        Ok(lightx::ext::hyper::Response::builder().status(200).header(lightx::ext::hyper::header::CONTENT_TYPE, \"{}\").header(lightx::ext::hyper::header::ETAG, etag).header(lightx::ext::hyper::header::CACHE_CONTROL, \"public, max-age=0, must-revalidate\").body(boxed_body).unwrap())\n", mime));
                                code.push_str("                    },\n");
                            }
                        }
                    }

                    code.push_str(
                        "                    _ => Err(lightx::core::AppError::RouteNotFound),\n",
                    );
                    code.push_str("                }\n");
                    code.push_str("            },\n");
                } else {
                    code.push_str(&format!(
                        "            {} => crate::{}::handle(ctx).await.map(|resp| resp.map(|b| lightx::ext::http_body_util::BodyExt::boxed(lightx::ext::http_body_util::BodyExt::map_err(b, |e| Box::new(e) as Box<dyn std::error::Error + Send + Sync + 'static>)))),\n",
                        current_node, handler_name
                    ));
                }
            }
        }

        code.push_str(&format!("            {} => {{\n", swagger_id));
        code.push_str("                Ok(lightx::ext::hyper::Response::builder().status(200).header(\"Content-Type\", \"application/json\").body(lightx::ext::http_body_util::BodyExt::boxed(lightx::ext::http_body_util::BodyExt::map_err(lightx::ext::http_body_util::Full::new(lightx::ext::bytes::Bytes::from(include_str!(concat!(env!(\"OUT_DIR\"), \"/openapi.json\")))), |e| Box::new(e) as Box<dyn std::error::Error + Send + Sync + 'static>))).unwrap())\n");
        code.push_str("            },\n");
        code.push_str("            _ => Err(lightx::core::AppError::RouteNotFound),\n");
        code.push_str("        }\n");
        code.push_str("    } else {\n");
        code.push_str("        Err(lightx::core::AppError::RouteNotFound)\n");
        code.push_str("    }\n");
        code.push_str("    }.instrument(span).await\n");
        code.push_str("}\n\n");

        code.push_str("#[derive(Clone)]\npub struct AppRouter {\n    pub factory: std::sync::Arc<crate::AppContextFactory>,\n}\n");
        code.push_str("impl lightx::server::Router for AppRouter {\n");
        code.push_str("    type Context = crate::RequestContext;\n");
        code.push_str("    fn route<'a>(\n");
        code.push_str("        &'a self,\n");
        code.push_str("        method: &'a str,\n");
        code.push_str("        uri: &'a str,\n");
        code.push_str("        ctx: &'a mut Self::Context,\n");
        code.push_str("    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<lightx::ext::hyper::Response<lightx::ext::http_body_util::combinators::BoxBody<lightx::ext::bytes::Bytes, Box<dyn std::error::Error + Send + Sync + 'static>>>, lightx::core::AppError>> + Send + 'a>> {\n");
        code.push_str("        Box::pin(route_request(method, uri, ctx))\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");

        fs::write(dest_path, code)?;
        println!(
            "cargo:warning= Core (Static Router) generation completed successfully in OUT_DIR!"
        );

        Ok(())
    }
}
