use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize)]
pub struct HandlerConfig {
    #[serde(default)]
    pub parameters: HashMap<String, String>,
    #[serde(default)]
    pub cache: Option<u64>,
    #[serde(default)]
    pub pipeline: Option<PipelineConfig>,
}

#[derive(Debug, Deserialize, Default, Clone)]
pub struct PipelineConfig {
    #[serde(default)]
    pub validations: Vec<String>,
    #[serde(default)]
    pub processings: Vec<String>,
}

///  `HandlerGenerator`: Orchestrates the AOP logic (Zero-Cost Abstraction).
///
/// This build-time struct parses `handlers/*.toml` configuration files and translates them
/// into procedural Rust code. By generating the pipeline directly into the source code,
/// the Rust compiler can aggressively inline operations and optimize away the overhead
/// traditionally associated with middleware patterns.
///
/// # Architecture
/// Instead of defining routes and middlewares at runtime using closures or function pointers,
/// LightX forces developers to declare their logic in TOML. The `HandlerGenerator` reads
/// this TOML and generates static `structs` that implement the `Handler` trait.
///
/// # Examples
///
/// ```no_run
/// use lightx::handler_generator::HandlerGenerator;
///
/// let generator = HandlerGenerator::new("./handlers", &std::env::var("OUT_DIR").unwrap());
/// generator.generate_handlers().expect("Failed to generate the Handlers");
/// ```
pub struct HandlerGenerator {
    handlers_dir: String,
    out_dir: String,
}

impl HandlerGenerator {
    /// Creates a new `HandlerGenerator` instance.
    ///
    /// # Arguments
    ///
    /// * `handlers_dir` - The root directory containing the TOML handler specifications.
    /// * `out_dir` - The `OUT_DIR` provided by Cargo during the build phase.
    pub fn new(handlers_dir: &str, out_dir: &str) -> Self {
        Self {
            handlers_dir: handlers_dir.to_string(),
            out_dir: out_dir.to_string(),
        }
    }

    fn visit_dirs(dir: &Path, cb: &mut dyn FnMut(&fs::DirEntry)) -> std::io::Result<()> {
        if dir.is_dir() {
            for entry in fs::read_dir(dir)? {
                let entry = entry?;
                let path = entry.path();
                if path.is_dir() {
                    Self::visit_dirs(&path, cb)?;
                } else {
                    cb(&entry);
                }
            }
        }
        Ok(())
    }

    /// Helper to convert a file system path into a valid Rust `PascalCase` struct identifier.
    /// (e.g., "api/AdminCreation" -> "ApiAdminCreation")
    fn to_pascal_name(rel_path: &Path) -> String {
        let mut name = String::new();
        for component in rel_path.components() {
            if let std::path::Component::Normal(os_str) = component {
                let mut s = os_str.to_string_lossy().into_owned();
                if s.ends_with(".toml") {
                    s.truncate(s.len() - 5);
                }
                let mut capitalize_next = true;
                for c in s.chars() {
                    if c == '-' || c == '_' || c == '{' || c == '}' || c == '.' {
                        capitalize_next = true;
                    } else if capitalize_next {
                        name.push_str(&c.to_uppercase().to_string());
                        capitalize_next = false;
                    } else {
                        name.push(c);
                    }
                }
            }
        }
        name
    }

    ///  Parses the TOML files and generates the Handlers
    pub fn generate_handlers(&self) -> Result<(), Box<dyn std::error::Error>> {
        let handlers_path = Path::new(&self.handlers_dir);
        if !handlers_path.exists() {
            // Handlers layer not yet used, just skip
            return Ok(());
        }

        let dest_path = Path::new(&self.out_dir).join("lightx_handlers_generated.rs");
        let mut code = String::from(
            "// =====================================================================\n// THIS FILE IS AUTO-GENERATED BY LIGHTX. DO NOT EDIT.\n// =====================================================================\n\n",
        );

        let mut toml_files = Vec::new();
        let mut openapi_paths = serde_json::Map::new();
        Self::visit_dirs(handlers_path, &mut |entry| {
            if entry.path().extension().unwrap_or_default() == "toml" {
                toml_files.push(entry.path());
            }
        })?;

        for path in toml_files {
            let rel_path = path.strip_prefix(handlers_path).unwrap();
            let base_name = Self::to_pascal_name(rel_path);
            let handler_name = format!("{}Handler", base_name);

            let content = fs::read_to_string(&path)?;
            let config: HandlerConfig = toml::from_str(&content)?;

            let action = rel_path.file_stem().unwrap().to_string_lossy().to_string();
            let parent_path = rel_path.parent().unwrap_or(Path::new(""));
            let bo_opt = if parent_path.as_os_str().is_empty() {
                None
            } else {
                parent_path
                    .file_name()
                    .map(|s| s.to_string_lossy().to_string())
            };
            let chemin_path = parent_path.parent().unwrap_or(Path::new(""));

            let mut pipeline = config.pipeline.unwrap_or_default();

            if pipeline.validations.is_empty() && pipeline.processings.is_empty() {
                if let Some(bo) = bo_opt {
                    let bo_pascal = {
                        let s = bo.clone();
                        if let Some(first) = s.chars().next() {
                            format!("{}{}", first.to_uppercase(), &s[first.len_utf8()..])
                        } else {
                            s
                        }
                    };

                    // Construct the absolute path to `src/bo/{chemin}/{bo}_bo.rs`
                    let mut bo_rs_path = Path::new(&self.handlers_dir)
                        .parent()
                        .unwrap()
                        .join("src")
                        .join("bo");
                    if !chemin_path.as_os_str().is_empty() {
                        bo_rs_path = bo_rs_path.join(chemin_path);
                    }
                    bo_rs_path = bo_rs_path.join(format!("{}_bo.rs", bo));

                    // Construct the Rust module prefix
                    let mut module_prefix = String::new();
                    if !chemin_path.as_os_str().is_empty() {
                        for component in chemin_path.components() {
                            if let std::path::Component::Normal(os_str) = component {
                                module_prefix.push_str(&os_str.to_string_lossy());
                                module_prefix.push_str("::");
                            }
                        }
                    }

                    if bo_rs_path.exists() {
                        let bo_content = fs::read_to_string(&bo_rs_path).unwrap_or_default();

                        let val_fn_name = format!("check_{}_business_rules", action);
                        if bo_content.contains(&val_fn_name) {
                            pipeline.validations.push(format!(
                                "{}{}_bo::{}Bo::{}",
                                module_prefix, bo, bo_pascal, val_fn_name
                            ));
                        }

                        let proc_fn_name = action.clone();
                        if bo_content.contains(&format!("fn {}", proc_fn_name)) {
                            pipeline.processings.push(format!(
                                "{}{}_bo::{}Bo::{}",
                                module_prefix, bo, bo_pascal, proc_fn_name
                            ));
                        } else {
                            return Err(format!("AOP Auto-Wiring Error: The action function `pub async fn {}` is missing in `{}`. Required by handler `{}`", proc_fn_name, bo_rs_path.display(), path.display()).into());
                        }
                    } else {
                        return Err(format!("AOP Auto-Wiring Error: The Business Object file `{}` is missing. Required by handler `{}`", bo_rs_path.display(), path.display()).into());
                    }
                } else {
                    return Err(format!("AOP Auto-Wiring Error: Handler `{}` is at the root directory but has no [pipeline] defined. Root handlers require explicit pipeline configuration.", path.display()).into());
                }
            }

            let has_params = !config.parameters.is_empty();
            let payload_name = format!("{}Payload", base_name);

            let mut oas_properties = serde_json::Map::new();
            let mut oas_required = Vec::new();

            if has_params {
                let mut struct_fields = String::new();

                // Read schema to find types and constraints
                let mut field_metas = HashMap::new();
                for (param_name, schema_path) in &config.parameters {
                    let meta: daox::ColumnMetadata = if schema_path.is_empty() {
                        let override_dir = std::env::var("LIGHTX_OVERRIDES_DIR")
                            .map(std::path::PathBuf::from)
                            .unwrap_or_else(|_| {
                                Path::new(&self.handlers_dir)
                                    .parent()
                                    .unwrap()
                                    .join("overrides")
                            });
                        let virtual_toml_path = override_dir
                            .join("virtual")
                            .join(format!("{}.toml", param_name));

                        if !virtual_toml_path.exists() {
                            return Err(format!("AOP Mapping Error: Virtual parameter `{}` in handler `{}` requires a schema definition in `{}`. File not found.", param_name, path.display(), virtual_toml_path.display()).into());
                        }

                        let virtual_content = fs::read_to_string(&virtual_toml_path)?;
                        let col_override: daox::ColumnOverride = toml::from_str(&virtual_content)
                            .map_err(|e| {
                            format!(
                                "AOP Mapping Error: Failed to parse virtual schema `{}`: {}",
                                virtual_toml_path.display(),
                                e
                            )
                        })?;

                        daox::ColumnMetadata {
                            rust_type: col_override
                                .rust_type
                                .unwrap_or(daox::Property::Simple("String".to_string())),
                            is_optional: col_override
                                .is_optional
                                .unwrap_or(daox::Property::Simple(false)),
                            min_length: col_override.min_length,
                            max_length: col_override.max_length,
                            min_value: col_override.min_value,
                            max_value: col_override.max_value,
                            format: col_override.format,
                            enum_values: col_override.enum_values,
                            is_primary_key: daox::Property::Simple(false),
                            is_auto_increment: daox::Property::Simple(false),
                            business_rules: col_override.business_rules.unwrap_or_default(),
                        }
                    } else {
                        let parts: Vec<&str> = schema_path.split('.').collect();
                        if parts.len() != 2 {
                            return Err(format!(
                                "AOP Mapping Error: Parameter `{}` in handler `{}` is mapped to `{}`. It MUST follow the format `table_name.column_name` or be left empty `\"\"` for virtual parameters.",
                                param_name, path.display(), schema_path
                            ).into());
                        }

                        let table = parts[0];
                        let column = parts[1];
                        let schema_dir = std::env::var("LIGHTX_SCHEMA_DIR")
                            .map(std::path::PathBuf::from)
                            .unwrap_or_else(|_| {
                                Path::new(&self.handlers_dir)
                                    .parent()
                                    .unwrap()
                                    .join("schema")
                            });
                        let col_toml_path = schema_dir.join(table).join(format!("{}.toml", column));

                        if !col_toml_path.exists() {
                            return Err(format!(
                                "AOP Mapping Error: Cannot map parameter `{}` in handler `{}`. The database column `{}` does not exist in the schema (file not found: {}).",
                                param_name, path.display(), schema_path, col_toml_path.display()
                            ).into());
                        }

                        let col_content = fs::read_to_string(&col_toml_path)?;
                        toml::from_str(&col_content).map_err(|e| {
                            format!(
                                "AOP Mapping Error: Failed to parse `{}`: {}",
                                col_toml_path.display(),
                                e
                            )
                        })?
                    };

                    if meta.is_optional.value() && meta.is_optional.default_val().is_none() {
                        return Err(format!("AOP Schema Error: Parameter `{}` in schema for handler `{}` is marked as optional but lacks a mandatory `default` value.", param_name, path.display()).into());
                    }

                    let field_type = meta.rust_type.value();
                    let type_str = if field_type.starts_with("Option<") {
                        &field_type[7..field_type.len() - 1]
                    } else {
                        field_type.as_str()
                    };
                    let oas_type = match type_str {
                        "i32" | "u32" | "i64" | "u64" | "f64" => "number",
                        "bool" => "boolean",
                        _ => "string",
                    };
                    oas_properties
                        .insert(param_name.clone(), serde_json::json!({ "type": oas_type }));
                    if !meta.is_optional.value() {
                        oas_required.push(serde_json::json!(param_name.clone()));
                    }

                    if let Some(def_val) = meta.is_optional.default_val() {
                        if let Some(enum_prop) = &meta.enum_values {
                            let vals = enum_prop.value();
                            if !vals.is_empty() && !vals.contains(&def_val) {
                                return Err(format!("AOP Schema Error: The `default` value for `{}` ('{}') is not in the allowed `enum_values` list {:?}.", param_name, def_val, vals).into());
                            }
                        }
                        if let Some(max_len) = &meta.max_length
                            && def_val.len() > max_len.value()
                        {
                            return Err(format!("AOP Schema Error: The `default` value for `{}` exceeds max_length parameter of {}.", param_name, max_len.value()).into());
                        }
                        if let Some(min_len) = &meta.min_length
                            && def_val.len() < min_len.value()
                        {
                            return Err(format!("AOP Schema Error: The `default` value for `{}` is below min_length parameter of {}.", param_name, min_len.value()).into());
                        }
                        if let Some(format_prop) = &meta.format {
                            match regex::Regex::new(&format_prop.value()) {
                                Ok(re) => {
                                    if !re.is_match(&def_val) {
                                        return Err(format!("AOP Schema Error: The `default` value for `{}` ('{}') does not match the format regex '{}'.", param_name, def_val, format_prop.value()).into());
                                    }
                                }
                                Err(e) => {
                                    return Err(format!("AOP Schema Error: Invalid format regex '{}' defined for parameter `{}`: {}", format_prop.value(), param_name, e).into());
                                }
                            }
                        }
                        if meta.min_value.is_some() || meta.max_value.is_some() {
                            if let Ok(parsed_val) = def_val.parse::<f64>() {
                                if let Some(max_val) = &meta.max_value
                                    && parsed_val > (max_val.value() as f64)
                                {
                                    return Err(format!("AOP Schema Error: The `default` value for `{}` exceeds max_value of {}.", param_name, max_val.value()).into());
                                }
                                if let Some(min_val) = &meta.min_value
                                    && parsed_val < (min_val.value() as f64)
                                {
                                    return Err(format!("AOP Schema Error: The `default` value for `{}` is under min_value of {}.", param_name, min_val.value()).into());
                                }
                            } else {
                                return Err(format!("AOP Schema Error: The `default` numeric value '{}' for `{}` cannot be parsed.", def_val, param_name).into());
                            }
                        }
                    }

                    field_metas.insert(param_name.clone(), meta.clone());
                    let field_type = meta.rust_type.value();
                    if meta.is_optional.value() {
                        if let Some(def_val) = meta.is_optional.default_val() {
                            let fn_name = format!(
                                "_def_{}_{}",
                                payload_name.to_lowercase(),
                                param_name.to_lowercase()
                            );
                            if field_type == "String" {
                                code.push_str(&format!(
                                    "fn {}() -> {} {{ \"{}\".to_string() }}\n",
                                    fn_name, field_type, def_val
                                ));
                            } else {
                                code.push_str(&format!(
                                    "fn {}() -> {} {{ \"{}\".parse().unwrap() }}\n",
                                    fn_name, field_type, def_val
                                ));
                            }
                            struct_fields
                                .push_str(&format!("    #[serde(default = \"{}\")]\n", fn_name));
                        } else {
                            struct_fields.push_str("    #[serde(default)]\n");
                        }
                    }
                    struct_fields.push_str(&format!("    pub {}: {},\n", param_name, field_type));
                }
                code.push_str("#[derive(Debug, Clone, serde::Deserialize)]\n");
                code.push_str(&format!("pub struct {} {{\n", payload_name));
                code.push_str(&struct_fields);
                code.push_str("}\n\n");

                code.push_str(&format!("pub struct {};\n\n", handler_name));
                code.push_str(&format!("impl {} {{\n", handler_name));

                // check_parameters Generation: deserializes directly from raw_body bytes (True Zero-Copy)
                code.push_str(
                    "    ///  Validation et Extraction Sécurisée (Parse, don't validate)\n",
                );
                code.push_str(&format!("    pub fn check_parameters(ctx: &crate::RequestContext) -> Result<{}, lightx::core::AppError> {{\n", payload_name));
                code.push_str("        let body_bytes = if ctx.raw_body.is_empty() { b\"{}\".as_slice() } else { &ctx.raw_body };\n");
                code.push_str(&format!("        let payload: {} = lightx::ext::serde_json::from_slice(body_bytes).map_err(|e| lightx::core::AppError::ParameterError {{ field: \"body\".into(), msg: format!(\"Malformed JSON: {{}}\", e).into(), file: file!(), line: line!() }})?;\n\n", payload_name));

                // 2. Validation Phase directly on the parsed struct
                for (param_name, meta) in &field_metas {
                    let field_type = meta.rust_type.value();

                    let val_ref = format!("payload.{}", param_name);
                    let val_deref = format!("payload.{}", param_name);
                    let val_addr = format!("&payload.{}", param_name);

                    let mut has_eval = false;
                    if let Some(enum_prop) = &meta.enum_values {
                        let vals = enum_prop.value();
                        if !vals.is_empty() {
                            let match_arms = vals
                                .iter()
                                .map(|v| format!("\"{}\"", v))
                                .collect::<Vec<_>>()
                                .join(" | ");
                            let msg = enum_prop
                                .message()
                                .unwrap_or_else(|| "Invalid value".to_string());
                            let val_cmp =
                                if field_type == "String" || field_type == "Option<String>" {
                                    format!("{}.as_str()", val_ref)
                                } else {
                                    format!("{}.to_string().as_str()", val_deref)
                                };
                            code.push_str(&format!(
                                "            if !matches!({}, {}) {{\n",
                                val_cmp, match_arms
                            ));
                            code.push_str(&format!("                return Err(lightx::core::AppError::ParameterError {{ field: \"{}\".into(), msg: \"{}\".into(), file: file!(), line: line!() }});\n", param_name, msg));
                            code.push_str("            }\n");
                            has_eval = true;
                        }
                    }

                    if !has_eval {
                        if field_type == "String" || field_type == "Option<String>" {
                            if let Some(max_prop) = &meta.max_length {
                                let max = max_prop.value();
                                let msg = max_prop.message().unwrap_or_else(|| {
                                    format!("Exceeds maximum length of {}", max)
                                });
                                code.push_str(&format!(
                                    "            if {}.len() > {} {{\n",
                                    val_ref, max
                                ));
                                code.push_str(&format!("                return Err(lightx::core::AppError::ParameterError {{ field: \"{}\".into(), msg: \"{}\".into(), file: file!(), line: line!() }});\n", param_name, msg));
                                code.push_str("            }\n");
                            }
                            if let Some(min_prop) = &meta.min_length {
                                let min = min_prop.value();
                                if min > 0 {
                                    let msg = min_prop.message().unwrap_or_else(|| {
                                        format!("Under minimum length of {}", min)
                                    });
                                    if min == 1 {
                                        code.push_str(&format!(
                                            "            if {}.is_empty() {{\n",
                                            val_ref
                                        ));
                                    } else {
                                        code.push_str(&format!(
                                            "            if {}.len() < {} {{\n",
                                            val_ref, min
                                        ));
                                    }
                                    code.push_str(&format!("                return Err(lightx::core::AppError::ParameterError {{ field: \"{}\".into(), msg: \"{}\".into(), file: file!(), line: line!() }});\n", param_name, msg));
                                    code.push_str("            }\n");
                                }
                            }
                            if let Some(format_prop) = &meta.format {
                                let regex_str = format_prop.value();
                                let msg = format_prop
                                    .message()
                                    .unwrap_or_else(|| "Invalid format".to_string());
                                code.push_str(&format!("            static RE_{}: std::sync::LazyLock<lightx::ext::regex::Regex> = std::sync::LazyLock::new(|| lightx::ext::regex::Regex::new(r#\"{}\"#).expect(\"Regex pre-validated by generator\"));\n", param_name.to_uppercase(), regex_str));
                                code.push_str(&format!(
                                    "            if !RE_{}.is_match({}) {{\n",
                                    param_name.to_uppercase(),
                                    val_addr
                                ));
                                code.push_str(&format!("                return Err(lightx::core::AppError::ParameterError {{ field: \"{}\".into(), msg: \"{}\".into(), file: file!(), line: line!() }});\n", param_name, msg));
                                code.push_str("            }\n");
                            }
                        } else if field_type != "bool" && field_type != "Option<bool>" {
                            if let Some(max_prop) = &meta.max_value {
                                let max = max_prop.value();
                                let msg = max_prop
                                    .message()
                                    .unwrap_or_else(|| format!("Exceeds maximum value of {}", max));
                                code.push_str(&format!(
                                    "            if ({} as f64) > {}.0 {{\n",
                                    val_deref, max
                                ));
                                code.push_str(&format!("                return Err(lightx::core::AppError::ParameterError {{ field: \"{}\".into(), msg: \"{}\".into(), file: file!(), line: line!() }});\n", param_name, msg));
                                code.push_str("            }\n");
                            }
                            if let Some(min_prop) = &meta.min_value {
                                let min = min_prop.value();
                                let msg = min_prop
                                    .message()
                                    .unwrap_or_else(|| format!("Under minimum value of {}", min));
                                code.push_str(&format!(
                                    "            if ({} as f64) < {}.0 {{\n",
                                    val_deref, min
                                ));
                                code.push_str(&format!("                return Err(lightx::core::AppError::ParameterError {{ field: \"{}\".into(), msg: \"{}\".into(), file: file!(), line: line!() }});\n", param_name, msg));
                                code.push_str("            }\n");
                            }
                        }
                    }
                }
                code.push_str("        Ok(payload)\n");
                code.push_str("    }\n\n");
            } else {
                code.push_str(&format!("pub struct {};\n\n", handler_name));
                code.push_str(&format!("impl {} {{\n", handler_name));
            }

            code.push_str("    pub async fn handle(ctx: &mut crate::RequestContext) -> Result<lightx::ext::hyper::Response<lightx::ext::http_body_util::Full<lightx::ext::bytes::Bytes>>, lightx::core::AppError> {\n");

            if config.cache.is_some() {
                code.push_str("        // CACHE RADICAL: Pre-condition\n");
                code.push_str("        use std::hash::{Hash, Hasher};\n");
                code.push_str(
                    "        let mut _hasher = std::collections::hash_map::DefaultHasher::new();\n",
                );
                code.push_str("        ctx.raw_body.hash(&mut _hasher);\n");
                code.push_str(&format!(
                    "        let cache_key = format!(\"{}_{{}}\", _hasher.finish());\n",
                    rel_path.display()
                ));
                code.push_str(
                    "        if let Some(cached_resp) = ctx.response_cache.get(&cache_key) {\n",
                );
                code.push_str("            if cached_resp.3 > std::time::Instant::now() {\n");
                code.push_str("                let mut builder = lightx::ext::hyper::Response::builder().status(cached_resp.0);\n");
                code.push_str("                for (k, v) in cached_resp.1.iter() {\n");
                code.push_str("                    builder = builder.header(k, v);\n");
                code.push_str("                }\n");
                code.push_str("                return Ok(builder.body(lightx::ext::http_body_util::Full::new(cached_resp.2.clone())).unwrap());\n");
                code.push_str("            } else {\n");
                code.push_str("                ctx.response_cache.invalidate(&cache_key);\n");
                code.push_str("            }\n");
                code.push_str("        }\n\n");
            }

            if has_params {
                // The handler immediately calls check_parameters and retains the typed payload
                code.push_str("        let payload = Self::check_parameters(ctx)?;\n\n");
            }

            code.push_str("        // ==========================================\n");
            code.push_str("        // ETAPE 1 : PIPELINE DE VALIDATION (Fail-Fast)\n");
            code.push_str("        // ==========================================\n");
            for validation in pipeline.validations {
                if has_params {
                    code.push_str(&format!(
                        "        crate::bo::{}(ctx, &payload).await?;\n",
                        validation
                    ));
                } else {
                    code.push_str(&format!("        crate::bo::{}(ctx).await?;\n", validation));
                }
            }

            code.push_str("\n        // ==========================================\n");
            code.push_str("        // ETAPE 2 : PIPELINE DE TRAITEMENT (Transactionnel)\n");
            code.push_str("        // ==========================================\n");
            let p_len = pipeline.processings.len();
            for (i, processing) in pipeline.processings.into_iter().enumerate() {
                let is_last = i == p_len - 1;
                let var_bind = if is_last { "let resp = " } else { "" };
                if has_params {
                    code.push_str(&format!(
                        "        {}crate::bo::{}(ctx, &payload).await?;\n",
                        var_bind, processing
                    ));
                } else {
                    code.push_str(&format!(
                        "        {}crate::bo::{}(ctx).await?;\n",
                        var_bind, processing
                    ));
                }
            }

            if p_len == 0 {
                code.push_str("        let resp = lightx::ext::hyper::Response::builder().status(200).header(\"Content-Type\", \"application/json\").body(lightx::ext::http_body_util::Full::new(lightx::ext::bytes::Bytes::from(\"{\\\"status\\\":\\\"success\\\"}\"))).unwrap();\n");
            }

            if let Some(ttl) = config.cache {
                code.push_str("        // CACHE RADICAL: Storage\n");
                code.push_str("        let (parts, body) = resp.into_parts();\n");
                code.push_str("        use lightx::ext::http_body_util::BodyExt;\n");
                code.push_str("        let bytes_body = body.collect().await.map_err(|e| lightx::core::AppError::SystemError { msg: e.to_string(), file: file!(), line: line!() })?.to_bytes();\n");
                code.push_str(&format!("        let expiry = std::time::Instant::now() + std::time::Duration::from_secs({});\n", ttl));
                code.push_str("        ctx.response_cache.insert(cache_key, (parts.status, parts.headers.clone(), bytes_body.clone(), expiry));\n");
                code.push_str("        let resp = lightx::ext::hyper::Response::from_parts(parts, lightx::ext::http_body_util::Full::new(bytes_body));\n");
            }

            code.push_str("\n        Ok(resp)\n");
            code.push_str("    }\n");
            code.push_str("}\n\n");
            let mut segments = Vec::new();
            for component in rel_path.components() {
                if let std::path::Component::Normal(os_str) = component {
                    let mut s = os_str.to_string_lossy().into_owned();
                    if s.ends_with(".toml") {
                        s.truncate(s.len() - 5);
                    }
                    let kebab = s
                        .chars()
                        .enumerate()
                        .map(|(i, c)| {
                            if c.is_uppercase() {
                                format!("{}{}", if i > 0 { "-" } else { "" }, c.to_lowercase())
                            } else {
                                c.to_string()
                            }
                        })
                        .collect::<String>();
                    segments.push(kebab);
                }
            }
            let route_uri = format!("/{}", segments.join("/"));

            openapi_paths.insert(
                route_uri,
                serde_json::json!({
                    "post": {
                        "summary": handler_name,
                        "requestBody": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": oas_properties,
                                        "required": oas_required
                                    }
                                }
                            }
                        },
                        "responses": {
                            "200": { "description": "OK" }
                        }
                    }
                }),
            );
        }

        let openapi_doc = serde_json::json!({
            "openapi": "3.0.0",
            "info": {
                "title": "LightX API",
                "version": "1.0.0"
            },
            "paths": openapi_paths
        });

        let openapi_path = Path::new(&self.out_dir).join("openapi.json");
        fs::write(
            openapi_path,
            serde_json::to_string_pretty(&openapi_doc).unwrap(),
        )?;

        fs::write(dest_path, code)?;
        println!("cargo:warning= Handlers (AOP) generation completed successfully in OUT_DIR!");

        Ok(())
    }
}
