[type]
value = "String"
message = "schema.type.message"

[is_optional]
value = false
message = "schema.is_optional.message"

# [enum_values]
# value = []
# message = 

[max_length]
value = 50
message = "schema.max_length.message|50"

[min_length]
value = 1
message = "schema.min_length.message|1"

# [min_value]
# value = 
# message = 

# [max_value]
# value = 
# message = 

[format]
value = '^[À-ÿA-Za-z0-9_ -]*$'
message = "schema.format.message"

[is_primary_key]
value = true

[is_auto_increment]
value = false

[business_rules]

