[type]
value = "String"
message = "schema.type.message"

[is_optional]
value = false
message = "schema.is_optional.message"

[enum_values]
value = ["tech", "food", "books"]
message = "schema.enum_values.message"

[max_length]
value = 5
message = "schema.max_length.message|5"

[min_length]
value = 1
message = "schema.min_length.message|1"

# [min_value]
# value = 
# message = 

# [max_value]
# value = 
# message = 

[format]
value = '^(tech|food|books)$'
message = "schema.format.message"

[is_primary_key]
value = false

[is_auto_increment]
value = false

[business_rules]

