[business_rules]

[enum_values]
value = []

[format]
message = "schema.format.message"
value = "^[0-9]{1,16}$"

[has_default]
value = false

[is_auto_increment]
value = false

[is_generated]
value = false

[is_index]
value = false

[is_optional]
message = "schema.is_optional.message"
value = false

[is_primary_key]
value = true

[is_unique]
value = false

[max_length]
message = "schema.max_length.message|16"
value = 16

[min_length]
message = "schema.min_length.message|1"
value = 1

[type]
message = "schema.type.message"
value = "Vec<u8>"
