[business_rules]

[enum_values]
value = []

[format]
message = "schema.format.message"
value = "^.*$"

[has_default]
value = false

[is_auto_increment]
value = false

[is_generated]
value = false

[is_index]
value = false

[is_optional]
default = ""
message = ""
value = true

[is_primary_key]
value = false

[is_unique]
value = false

[max_length]
message = "schema.max_length.message|65535"
value = 65535

[min_length]
message = "schema.min_length.message|0"
value = 0

[type]
message = "schema.type.message"
value = "Vec<u8>"
