//! # Homepage Implementation
//!
//! This module manages the landing page of the application, demonstrating how to serve
//! beautifully styled HTML using `tmplx` generated macros.

use lightx::core::AppError;
use lightx::ext::bytes::Bytes;
use lightx::ext::http_body_util::Full;
use lightx::ext::hyper::Response;

use crate::generated::TMPLX_STATIC_SIZE_RENDER_INDEX;

/// Represents the data context passed to the template.
/// In this case, the homepage is static, so the context is empty.
pub struct HomeViewData {}

/// The main handler for the index route (GET /).
///
/// This asynchronous function allocates a precisely sized String buffer,
/// writes the structurally validated template into it, and serves it as a fast HTTP response.
pub async fn home_index(
    _ctx: &mut crate::RequestContext,
) -> Result<Response<Full<Bytes>>, AppError> {
    let view_data = HomeViewData {};

    // Allocate the buffer synchronously with O(1) capacity estimation.
    // We add a safety padding of 2000 bytes for dynamic content sizes if any.
    let mut html = String::with_capacity(TMPLX_STATIC_SIZE_RENDER_INDEX + 2000);

    // Invoke the macro generated by the `tmplx` template engine.
    render_index!(&mut html, &view_data);

    // Build and return the successful HTTP Response.
    Ok(Response::builder()
        .status(200)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Full::new(Bytes::from(html)))
        .unwrap())
}
