#![allow(clippy::all)]
//!  `lightx-test`: The Verification Sandbox
//!
//! This executable demonstrates how a "Database-First" architecture integrates
//! with the user's application code.
use std::env;

pub mod bo;
pub mod supertest;
const _CHANGELOG_VALIDATION: &str = include_str!("../../lightx/CHANGELOG.md");

// =====================================================================
// 1. NATIVE INCLUSION OF GENERATED DAO
// =====================================================================
// Instead of writing redundant structs, we dynamically inject the DAO
// generated by `build.rs`. This file lives safely in `OUT_DIR`, preventing
// git pollution while offering 100% Rust compiler type-safety and autocompletion.
pub mod daox_generated;
pub use daox_generated::*;

// =====================================================================
// 1b. NATIVE INCLUSION OF GENERATED HANDLERS (AOP)
// =====================================================================
include!(concat!(env!("OUT_DIR"), "/lightx_handlers_generated.rs"));

// =====================================================================
// 1c. NATIVE INCLUSION OF GENERATED CORE ROUTER
// =====================================================================
include!(concat!(env!("OUT_DIR"), "/lightx_core_generated.rs"));

// =====================================================================
// 2. LAYER EXECUTIONS
// =====================================================================

///  Executes the Data Access Object (DAO) workflow.
async fn run_dao(
    factory: &std::sync::Arc<crate::AppContextFactory>,
) -> Result<(), Box<dyn std::error::Error>> {
    use lightx::server::ContextFactory;
    println!("\n---  TESTING DAO LAYER ---");
    let mut ctx = factory.create_context(
        "127.0.0.1".parse().unwrap(),
        lightx::ext::hyper::HeaderMap::new(),
        lightx::ext::bytes::Bytes::new(),
        None,
    );

    let currency = Currencies::get_by_code(&ctx.mysql_pool, &"EUR".to_string()).await?;

    if let Some(c) = currency {
        println!(" Currency found: {} ({})", c.name, c.code);
    } else {
        println!(" Currency not found (EUR).");
    }

    if let Some(tx) = ctx.mysql_tx.take() {
        tx.commit().await?;
        println!(" DAO Transaction committed to Database.");
    }

    Ok(())
}

///  Executes the Business Object (BO) workflow.
async fn run_bo(
    factory: &std::sync::Arc<crate::AppContextFactory>,
) -> Result<(), Box<dyn std::error::Error>> {
    use lightx::server::ContextFactory;
    println!("\n---  TESTING BO LAYER ---");
    let mut ctx = factory.create_context(
        "127.0.0.1".parse().unwrap(),
        lightx::ext::hyper::HeaderMap::new(),
        lightx::ext::bytes::Bytes::new(),
        None,
    );

    // We now inject raw JSON body bytes instead of a HashMap
    let json_body = serde_json::json!({
        "email": "boss@lightx.com",
        "first_name": "John",
        "last_name": "Doe",
        "accept_terms": true
    });
    ctx.raw_body = lightx::ext::bytes::Bytes::from(json_body.to_string());

    // check_parameters now returns the typed payload directly (no TypeMap)
    let payload = crate::AdminCreationHandler::check_parameters(&ctx)?;

    // Execute the BO: it will dynamically spawn a lazy transaction,
    // insert the User, and insert the UserRoles.
    match bo::user_bo::UserBo::execute_admin_creation(&mut ctx, &payload).await {
        Ok(resp) => println!(
            " Admin created successfully with Response status: {}",
            resp.status()
        ),
        Err(e) => println!(" Failed to create Admin: {}", e),
    }

    if let Some(tx) = ctx.mysql_tx.take() {
        tx.commit().await?;
        println!(" BO Transaction committed to Database.");
    }

    Ok(())
}

///  Executes the HTTP Handler logic (Validation layer).
async fn run_handler(
    factory: &std::sync::Arc<crate::AppContextFactory>,
) -> Result<(), Box<dyn std::error::Error>> {
    use lightx::server::ContextFactory;
    println!("\n---  TESTING HANDLER LAYER (AOP) ---");
    let mut ctx = factory.create_context(
        "127.0.0.1".parse().unwrap(),
        lightx::ext::hyper::HeaderMap::new(),
        lightx::ext::bytes::Bytes::new(),
        None,
    );

    // Injection of raw JSON body bytes (zero-copy approach)
    let json_body = serde_json::json!({
        "email": "vp@lightx.com",
        "first_name": "Jane",
        "last_name": "Smith",
        "accept_terms": true
    });
    ctx.raw_body = lightx::ext::bytes::Bytes::from(json_body.to_string());

    // Call the automatically generated Core Router !
    // Since AdminCreation.toml is at the root of `handlers/`, the URI is `/admin-creation`
    match route_request("POST", "/admin-creation", &mut ctx).await {
        Ok(_) => println!(" Core Router successfully matched URI and executed the AOP Handler!"),
        Err(e) => println!(" Core Router failed: {}", e),
    }

    if let Some(tx) = ctx.mysql_tx.take() {
        tx.commit().await?;
        println!(" Handler Transaction committed to Database.");
    }

    Ok(())
}

///  Executes the Pub/Sub WebSocket workflow (Verification of 5.1).
async fn run_pubsub(
    factory: &std::sync::Arc<crate::AppContextFactory>,
) -> Result<(), Box<dyn std::error::Error>> {
    use lightx::server::ContextFactory;
    println!("\n---  TESTING PUBSUB (WEBSOCKET SHARED STATE) ---");
    let mut ctx = factory.create_context(
        "127.0.0.1".parse().unwrap(),
        lightx::ext::hyper::HeaderMap::new(),
        lightx::ext::bytes::Bytes::new(),
        None,
    );

    // Simulate a pool of connected WebSocket clients listening to the global shared state
    let mut rx1 = ctx.global_state.subscribe();
    let mut rx2 = ctx.global_state.subscribe();

    let json_body = serde_json::json!({
        "email": "pubsub@lightx.com",
        "first_name": "Pub",
        "last_name": "Sub",
        "accept_terms": true
    });
    ctx.raw_body = lightx::ext::bytes::Bytes::from(json_body.to_string());
    let payload = crate::AdminCreationHandler::check_parameters(&ctx)?;

    // Simulate HTTP POST executing Business Object which will mutate the DB and Broadcast
    match bo::user_bo::UserBo::execute_admin_creation(&mut ctx, &payload).await {
        Ok(_) => println!(" Business Mutation executed, broadcasting to clients!"),
        Err(e) => println!(" Failed to execute BO for Pub/Sub: {}", e),
    }

    // Instantly receive messages on both clients without congestion
    let msg1: lightx::ext::bytes::Bytes = rx1.recv().await.unwrap();
    let msg2: lightx::ext::bytes::Bytes = rx2.recv().await.unwrap();

    println!(
        " WebSocket Client 1 received: {}",
        String::from_utf8_lossy(&msg1)
    );
    println!(
        " WebSocket Client 2 received: {}",
        String::from_utf8_lossy(&msg2)
    );
    assert_eq!(msg1, msg2);

    if let Some(tx) = ctx.mysql_tx.take() {
        tx.commit().await?;
        println!(" Pub/Sub Transaction committed to Database.");
    }
    Ok(())
}

async fn run_supertest(
    factory: std::sync::Arc<crate::AppContextFactory>,
) -> Result<(), Box<dyn std::error::Error>> {
    println!("\n--- 🧪 TESTING SUPERTEST MOCKING API ---");
    let app = crate::AppRouter { factory };

    // Simulate HTTP in memory natively via Tower
    let response = crate::supertest::SuperTest::get(app.clone(), "/public/test.css")
        .header(
            "if-none-match",
            "\"7a28aff6af5c05621605213cda37fef7022601ca541471732d5f32fff7ef77dc\"",
        )
        .send()
        .await;

    assert_eq!(
        response.status().as_u16(),
        304,
        "SuperTest Mocking API Failed!"
    );
    println!(" SuperTest executed 304 Not Modified perfectly in O(1) mathematically without TCP!");
    Ok(())
}

async fn run_background_tasks() -> Result<(), Box<dyn std::error::Error>> {
    println!("\n--- ⏳ TESTING ABSOLUTE DEFERRED TASKS ---");
    // Ensure the orchestrator is running
    lightx::server::init_background_orchestrator();

    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<()>();
    let start_time = std::time::Instant::now();

    // Simulating a Handler delegating a heavy task
    lightx::core::DeferredTask::spawn(async move {
        // Heavy blocking task detached from TCP
        tokio::time::sleep(tokio::time::Duration::from_millis(5000)).await;
        println!(" [BACKGROUND] 5-second heavy task finally completed!");
        let _ = tx.send(());
    });

    let elapsed = start_time.elapsed().as_millis();
    println!(
        " [HTTP] Response returned to user instantaneously out of handler in {}ms.",
        elapsed
    );
    assert!(
        elapsed < 10,
        "Task submission took too long, blocking the HTTP flow"
    );

    // Await strictly for test synchronization, otherwise main exits and kills Tokio
    rx.recv().await;
    println!(" Orchestrator successfully supervised Background Task to completion independently.");
    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!(" Starting LightX Test Suite...");

    // Load local environment variables from `.env` inside the `lightx-test` manifest directory.
    let env_path = format!("{}/.env", env!("CARGO_MANIFEST_DIR"));
    dotenvy::from_path(env_path).ok();

    let log_dir = std::env::var("LIGHTX_LOG_DIR").unwrap_or_else(|_| "./logs".to_string());

    // Initialisation du Logger Asynchrone
    lightx::logger::init(&log_dir).unwrap_or_else(|e| {
        panic!(
            " CRITICAL: Impossible d'initialiser le dossier de log '{}': {}",
            log_dir, e
        );
    });
    let log_lang = std::env::var("LIGHTX_LOG_LANG").unwrap_or_else(|_| "en".to_string());
    lightx::logger::info(crate::get_system_log("server.start", &log_lang).into());

    // Initialisation native OpenTelemetry OTLP
    if let Err(e) = lightx::logger::init_telemetry("lightx-test") {
        eprintln!(" WARN: Failed to initialize OpenTelemetry: {}", e);
    }
    let factory = std::sync::Arc::new(crate::AppContextFactory::new().await?);

    // Nettoyage des données de test précédentes pour éviter les erreurs SQL 1062
    sqlx::query("DELETE FROM users WHERE email IN ('boss@lightx.com', 'vp@lightx.com', 'pubsub@lightx.com')")
        .execute(&factory.mysql_pool)
        .await?;

    println!(" Successfully connected to database via factory!");

    // Execute each layer sequentially
    run_dao(&factory).await?;
    run_bo(&factory).await?;
    run_handler(&factory).await?;
    run_pubsub(&factory).await?;
    run_background_tasks().await?;
    run_supertest(factory.clone()).await?;

    println!("\n All LightX layers tested successfully!");

    println!("\n Starting TLS/HTTPS Server...");
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 8443));
    let _redirect_addr = std::net::SocketAddr::from(([127, 0, 0, 1], 8088));
    let cert_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../certs/lightx.loc.pem");
    let key_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../certs/lightx.loc.key");

    let router = std::sync::Arc::new(crate::AppRouter {
        factory: factory.clone(),
    });
    lightx::server::listen_tls(addr, factory, router, cert_path, key_path).await?;

    Ok(())
}
