#![allow(clippy::all)]
//!  `lightx-test`: The Verification Sandbox
//!
//! This executable demonstrates how a "Database-First" architecture integrates
//! with the user's application code.
use std::env;

pub mod bo;

const _CHANGELOG_VALIDATION: &str = include_str!("../../lightx/CHANGELOG.md");

// =====================================================================
// 1. NATIVE INCLUSION OF GENERATED DAO
// =====================================================================
// Instead of writing redundant structs, we dynamically inject the DAO
// generated by `build.rs`. This file lives safely in `OUT_DIR`, preventing
// git pollution while offering 100% Rust compiler type-safety and autocompletion.
include!(concat!(env!("OUT_DIR"), "/lightx_dao_generated.rs"));

// =====================================================================
// 1b. NATIVE INCLUSION OF GENERATED HANDLERS (AOP)
// =====================================================================
include!(concat!(env!("OUT_DIR"), "/lightx_handlers_generated.rs"));

// =====================================================================
// 1c. NATIVE INCLUSION OF GENERATED CORE ROUTER
// =====================================================================
include!(concat!(env!("OUT_DIR"), "/lightx_core_generated.rs"));

// =====================================================================
// 2. LAYER EXECUTIONS
// =====================================================================

///  Executes the Data Access Object (DAO) workflow.
async fn run_dao() -> Result<(), Box<dyn std::error::Error>> {
    println!("\n---  TESTING DAO LAYER ---");
    let mut ctx = RequestContext::new_sandbox_context().await.unwrap();

    println!(" Searching for currency 'EUR'...");
    let currency = Currencies::get_by_pk(&mut ctx, "EUR").await?;

    if let Some(c) = currency {
        println!(" Currency found: {} ({})", c.name, c.code);
    } else {
        println!(" Currency not found (EUR).");
    }

    if ctx.default_tx.is_some() {
        ctx.commit_default_tx().await?;
        println!(" DAO Transaction committed to Database.");
    }

    Ok(())
}

///  Executes the Business Object (BO) workflow.
async fn run_bo() -> Result<(), Box<dyn std::error::Error>> {
    println!("\n---  TESTING BO LAYER ---");
    let mut ctx = RequestContext::new_sandbox_context().await.unwrap();

    // We now inject raw JSON body bytes instead of a HashMap
    let json_body = serde_json::json!({
        "email": "boss@lightx.com",
        "first_name": "John",
        "last_name": "Doe",
        "accept_terms": true
    });
    ctx.raw_body = lightx::ext::bytes::Bytes::from(json_body.to_string());

    // check_parameters now returns the typed payload directly (no TypeMap)
    let payload = crate::AdminCreationHandler::check_parameters(&ctx)?;

    // Execute the BO: it will dynamically spawn a lazy transaction,
    // insert the User, and insert the UserRoles.
    match bo::user_bo::UserBo::execute_admin_creation(&mut ctx, &payload).await {
        Ok(resp) => println!(
            " Admin created successfully with Response status: {}",
            resp.status()
        ),
        Err(e) => println!(" Failed to create Admin: {}", e),
    }

    if ctx.default_tx.is_some() {
        ctx.commit_default_tx().await?;
        println!(" BO Transaction committed to Database.");
    }

    Ok(())
}

///  Executes the HTTP Handler logic (Validation layer).
async fn run_handler() -> Result<(), Box<dyn std::error::Error>> {
    println!("\n---  TESTING HANDLER LAYER (AOP) ---");
    let mut ctx = RequestContext::new_sandbox_context().await.unwrap();

    // Injection of raw JSON body bytes (zero-copy approach)
    let json_body = serde_json::json!({
        "email": "vp@lightx.com",
        "first_name": "Jane",
        "last_name": "Smith",
        "accept_terms": true
    });
    ctx.raw_body = lightx::ext::bytes::Bytes::from(json_body.to_string());

    // Call the automatically generated Core Router !
    // Since AdminCreation.toml is at the root of `handlers/`, the URI is `/admin-creation`
    match route_request("POST", "/admin-creation", &mut ctx).await {
        Ok(_) => println!(" Core Router successfully matched URI and executed the AOP Handler!"),
        Err(e) => println!(" Core Router failed: {}", e),
    }

    if ctx.default_tx.is_some() {
        ctx.commit_default_tx().await?;
        println!(" Handler Transaction committed to Database.");
    }

    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!(" Starting LightX Test Suite...");

    // Load local environment variables from `.env` inside the `lightx-test` manifest directory.
    let env_path = format!("{}/.env", env!("CARGO_MANIFEST_DIR"));
    dotenvy::from_path(env_path).ok();

    let log_dir = std::env::var("LIGHTX_LOG_DIR").unwrap_or_else(|_| "./logs".to_string());

    // Initialisation du Logger Asynchrone
    lightx::logger::init(&log_dir).unwrap_or_else(|e| {
        panic!(
            " CRITICAL: Impossible d'initialiser le dossier de log '{}': {}",
            log_dir, e
        );
    });
    let log_lang = std::env::var("LIGHTX_LOG_LANG").unwrap_or_else(|_| "en".to_string());
    lightx::logger::info(crate::get_system_log("server.start", &log_lang).into());

    // Initialisation native OpenTelemetry OTLP
    if let Err(e) = lightx::logger::init_telemetry("lightx-test") {
        eprintln!(" WARN: Failed to initialize OpenTelemetry: {}", e);
    }
    let factory = std::sync::Arc::new(crate::AppContextFactory::new().await?);

    // Nettoyage des données de test précédentes pour éviter les erreurs SQL 1062
    sqlx::query("DELETE FROM users WHERE email IN ('boss@lightx.com', 'vp@lightx.com')")
        .execute(&factory.default_pool)
        .await?;

    println!(" Successfully connected to database via factory!");

    // Execute each layer sequentially
    run_dao().await?;
    run_bo().await?;
    run_handler().await?;

    println!("\n All LightX layers tested successfully!");

    println!("\n Starting TLS/HTTPS Server...");
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 8443));
    let _redirect_addr = std::net::SocketAddr::from(([127, 0, 0, 1], 8088));
    let cert_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../certs/lightx.loc.pem");
    let key_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../certs/lightx.loc.key");

    let router = std::sync::Arc::new(crate::AppRouter);
    lightx::server::listen_tls(addr, factory, router, cert_path, key_path).await?;

    Ok(())
}
