[type]
value = "String"
message = "schema.type.message"

[is_optional]
value = true
message = ""

# [enum_values]
# value = []
# message = 

[min_length]
value = 0
message = "schema.min_length.message|0"

# [min_value]
# value = 
# message = 

# [max_value]
# value = 
# message = 

[format]
value = '^.*$'
message = "schema.format.message"

[is_primary_key]
value = false

[is_auto_increment]
value = false

[business_rules]
