[type]
value = "i64"
message = "schema.type.message"

[is_optional]
value = false
message = "schema.is_optional.message"

# [enum_values]
# value = []
# message = 

[max_length]
value = 19
message = "schema.max_length.message|19"

[min_length]
value = 1
message = "schema.min_length.message|1"

[min_value]
value = 0
message = "schema.min_value.message|0"

[max_value]
value = 9223372036854775807
message = "schema.max_value.message|9223372036854775807"

[format]
value = '^[0-9]{1,19}$'
message = "schema.format.message"

[is_primary_key]
value = true

[is_auto_increment]
value = false

[business_rules]

