[business_rules]

[enum_values]
value = []

[format]
message = "schema.format.message"
value = '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'

[has_default]
value = true

[is_auto_increment]
value = false

[is_generated]
value = true

[is_index]
value = false

[is_optional]
default = ""
message = ""
value = true

[is_primary_key]
value = false

[is_unique]
value = false

[min_length]
message = "schema.min_length.message|0"
value = 0

[type]
message = "schema.type.message"
value = "chrono::DateTime<chrono::Utc>"
