[package]
name = "lightx-web"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = ["validation"]
validation = []

[dependencies]
lightx = { path = "../lightx" }
tmplx = { path = "../../tmplx-workspace/tmplx" }
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite"] }
dotenvy = "0.15"
futures = "0.3.33"
regex = "1.13.1"

[build-dependencies]
daox = { version = "0.2.7", path = "../../daox-workspace/daox", default-features = false, features = [
    "sqlite",
] }
lightx = { path = "../lightx" }
tmplx = { path = "../../tmplx-workspace/tmplx" }
tokio = { version = "1.37.0", features = ["full"] }
dotenvy = "0.15"

[dev-dependencies]
lightx-macro = { path = "../lightx-macro" }
